using System;
using System.Collections.Generic;

namespace GaugeOMatic.Utility;

/// <summary>Traditional Chinese display-only translations for user-facing UI text.</summary>
internal static class UiText
{
    private static readonly Dictionary<string, string> Exact = new(StringComparer.Ordinal)
    {
        ["Layout"] = "配置",
        ["Colors"] = "顏色",
        ["Text"] = "文字",
        ["Behavior"] = "行為",
        ["Icon"] = "圖示",
        ["Sound"] = "音效",
        ["Widget"] = "元件",
        ["Widget Settings"] = "元件設定",
        ["Display Rules"] = "顯示規則",
        ["Visibility"] = "顯示條件",
        ["Anytime"] = "隨時",
        ["Combat / Duty Only"] = "僅戰鬥／任務中",
        ["Set Level Range"] = "限制等級範圍",
        ["Minimum Level"] = "最低等級",
        ["Maximum Level"] = "最高等級",
        ["Position"] = "位置",
        ["Scale"] = "縮放",
        ["Angle"] = "角度",
        ["Width"] = "寬度",
        ["Spacing"] = "間距",
        ["Speed"] = "速度",
        ["Threshold"] = "閾值",
        ["Midpoint"] = "中點",
        ["Direction"] = "方向",
        ["Fill Direction"] = "填充方向",
        ["Arrangement"] = "排列",
        ["Placement"] = "位置",
        ["Side"] = "側邊",
        ["Blend Mode"] = "混合模式",
        ["Animation"] = "動畫",
        ["Appear Animation"] = "出現動畫",
        ["Cooldown Style"] = "冷卻樣式",
        ["Precision "] = "精確度 ",
        ["Apply to:"] = "套用至：",
        ["Play Sound"] = "播放音效",
        ["Sound ID (0-79)"] = "音效 ID（0–79）",
        ["Override Text"] = "自訂文字",
        ["Show"] = "顯示",
        ["Hide"] = "隱藏",
        ["Show Icon"] = "顯示圖示",
        ["Show Zero "] = "顯示零值 ",
        ["Hide Empty"] = "空值時隱藏",
        ["When Empty"] = "空值時",
        ["Invert Fill"] = "反轉填充",
        ["Invert Value "] = "反轉數值 ",
        ["Mirror"] = "鏡像",
        ["Staggered"] = "交錯排列",
        ["Backdrop"] = "背景",
        ["Backplate"] = "底板",
        ["Base Color"] = "基底顏色",
        ["Base Tint"] = "基底色調",
        ["Bar Color"] = "量條顏色",
        ["Fill Color"] = "填充顏色",
        ["Border Color"] = "邊框顏色",
        ["Border Glow"] = "邊框發光",
        ["Glow Color"] = "發光顏色",
        ["Effects"] = "特效",
        ["Effects Color"] = "特效顏色",
        ["Flash"] = "閃光",
        ["Flash Color"] = "閃光顏色",
        ["Tick Color"] = "刻度顏色",
        ["Inactive"] = "未啟用",
        ["Active Backdrop"] = "啟用時背景",
        ["Inactive Backdrop"] = "未啟用時背景",
        ["Pulse"] = "脈衝",
        ["Pulse Colors"] = "脈衝顏色",
        ["Color Modifier"] = "顏色調整",
        ["Drain Color"] = "消耗顏色",
        ["Gain Color"] = "增加顏色",
        ["Frame Tint"] = "框架色調",
        ["Plate Tint"] = "底板色調",
        ["Ring Tint"] = "圓環色調",
        ["Orb Tint"] = "球體色調",
        ["Pearl Tint"] = "珍珠色調",
        ["Pearl Color"] = "珍珠顏色",
        ["Petal Color"] = "花瓣顏色",
        ["Scale Color"] = "鱗片顏色",
        ["Sparkles"] = "閃光粒子",
        ["Sparkle Effect"] = "閃光粒子效果",
        ["Petal Effect"] = "花瓣效果",
        ["Turn Smoothly"] = "平滑旋轉",
        ["None"] = "無",
        ["Left"] = "左",
        ["Right"] = "右",
        ["Up"] = "上",
        ["Down"] = "下",
        ["Horizontal"] = "水平",
        ["Vertical"] = "垂直",
        ["Clockwise"] = "順時針",
        ["Counterclockwise"] = "逆時針",
        ["Default"] = "預設",
        ["Enabled"] = "啟用",
        ["Disabled"] = "停用",
        ["Bar"] = "量條",
        ["Counter"] = "計數器",
        ["State Indicator"] = "狀態指示器",
        ["Job Gauge"] = "職業量譜",
        ["Status Effects"] = "狀態效果",
        ["Actions"] = "技能",
        ["Parameters"] = "參數",
        ["Search..."] = "搜尋……",
        ["Flank Venom"] = "側面毒素",
        ["Hind Venom"] = "背面毒素",
        ["Neutral / True North"] = "無指定／真北",
        ["Color-Code Vipersight"] = "依效果分類顯示蛇眼",
        ["Change color under Higi"] = "秘技期間變更顏色",
        ["Aetherflow Gems"] = "以太超流寶石",
        ["Addersgall Gems"] = "蛇膽寶石",
        ["Mana Diamonds"] = "魔元菱晶",
        ["Chakra Bar"] = "鬥氣量條",
        ["Coil Diamonds"] = "響尾蛇菱晶",
        ["Dragon Scales"] = "龍鱗",
        ["Elemental Crystals"] = "元素水晶",
        ["Polyglot Gems"] = "通曉寶石",
        ["Umbral Hearts"] = "靈極心",
        ["Kazematoi Kunai"] = "風纏苦無",
        ["Palette Pearls"] = "調色盤珍珠",
        ["Shroud Flames"] = "夜遊魂火焰",
        ["Meditation Gems"] = "劍壓寶石",
        ["Simple Gems"] = "簡易寶石",
        ["Addersgall Bar"] = "蛇膽量條",
        ["Arrow Bar"] = "箭形量條",
        ["Blood Blade"] = "暗血之刃",
        ["Beast Bar"] = "獸魂量條",
        ["Balance Bar"] = "平衡量條",
        ["Balance Gauge Overlay"] = "平衡量譜覆蓋層",
        ["Dragon Spear"] = "龍槍",
        ["Enochian Bar"] = "天語量條",
        ["Esprit Bar"] = "伶俐量條",
        ["Faerie Bar"] = "異想以太量條",
        ["Battery Gauge"] = "電能量譜",
        ["Heat Gauge"] = "熱度量譜",
        ["Huton Pinwheel"] = "風遁風車",
        ["InkSlash Gauge"] = "墨痕量譜",
        ["Kenki Katana"] = "劍氣武士刀",
        ["Kazematoi Bar"] = "風纏量條",
        ["Mahjong Ribbon"] = "麻將緞帶",
        ["Ninki Borders"] = "忍氣邊框",
        ["Ninki Overlay"] = "忍氣覆蓋層",
        ["Ninki Scroll"] = "忍氣卷軸",
        ["Oath Bar"] = "忠義量條",
        ["Simple Bar"] = "簡易量條",
        ["Simple Circle"] = "簡易圓環",
        ["Simple Timer"] = "簡易計時器",
        ["Soul Bar"] = "靈魂量條",
        ["Blood Gem"] = "暗血寶石",
        ["Beast Gem"] = "獸魂寶石",
        ["Balance Gauge Backplate"] = "平衡量譜底板",
        ["Dragon Eye"] = "龍眼",
        ["Elemental Orb"] = "元素球",
        ["Eukrasia Sigil"] = "均衡徽記",
        ["Faerie Frame"] = "異想以太框架",
        ["Finish Icon"] = "舞步結束圖示",
        ["Battery Gauge Overlay"] = "電能量譜覆蓋層",
        ["Heat Gauge Overlay"] = "熱度量譜覆蓋層",
        ["Kazematoi Swoosh"] = "風纏流光",
        ["Oath Sigil"] = "忠義徽記",
        ["Oath Gem"] = "忠義寶石",
        ["Parameter Bar Glow"] = "參數量條發光",
        ["Sen Seal"] = "閃印",
        ["Shimmering Halo"] = "微光光環",
        ["Target Reticle"] = "目標準星",
        ["Firstminds' Focus"] = "龍眼雷電",
        ["Kazematoi Stacks"] = "風纏層數",
        ["Meditation Gauge"] = "劍壓量譜",
        ["Setsu Seal"] = "雪之閃",
        ["Getsu Seal"] = "月之閃",
        ["Ka Seal"] = "花之閃",
        ["Seal Count"] = "閃數量",
        ["Shroud Gauge"] = "夜遊魂量譜",
        ["Lemure Shroud"] = "夜遊魂",
        ["Void Shroud"] = "虛無魂",
        ["Rattling Coils"] = "響尾蛇",
        ["Anguine Tribute"] = "蛇血貢品",
        ["Song Tracker (Any)"] = "詩歌追蹤器（任意）",
        ["Mage's Ballad"] = "賢者的敘事謠",
        ["Army's Paeon"] = "軍神的讚美歌",
        ["Wanderer's Minuet"] = "放浪神的小步舞曲",
        ["Automaton Timer"] = "自動人偶計時器",
        ["Esprit Gauge"] = "伶俐量譜",
        ["Dance Steps"] = "舞步",
        ["Enochian / Polyglot"] = "天語／通曉",
        ["Element Status"] = "元素狀態",
        ["Paradox"] = "悖論",
        ["Astral Soul Stacks"] = "星極魂層數",
        ["Fire Attunement"] = "火神調和",
        ["Earth Attunement"] = "土神調和",
        ["Wind Attunement"] = "風神調和",
        ["Summon Phase"] = "召喚階段",
        ["Mana Stacks"] = "魔元層數",
        ["Balance Crystal"] = "平衡水晶",
        ["Creature Motif Deadline"] = "生物意象復唱",
        ["Weapon Motif Deadline"] = "武器意象復唱",
        ["Landscape Motif Deadline"] = "風景意象復唱",
        ["Lilies"] = "百合",
        ["Blood Lily"] = "血百合",
        ["Fae Aether"] = "異想以太",
        ["Seraph Timer"] = "熾天使計時器",
        ["Eukrasia"] = "均衡",
        ["Addersting Counter"] = "蛇刺計數器",
        ["JobHudDRK0"] = "暗血量譜",
        ["JobHudDRK1"] = "暗黑量譜",
        ["JobHudGNB0"] = "晶壤量譜",
    };

    private static readonly (string English, string Chinese)[] Terms =
    [
        ("Serpent Offerings", "蛇之靈力"),
        ("Soul Voice", "靈魂之聲"),
        ("Fourfold Feathers", "幻扇"),
        ("Aetherflow", "以太超流"),
        ("Addersgall", "蛇膽"),
        ("Addersting", "蛇刺"),
        ("Astral Fire", "星極火"),
        ("Umbral Ice", "靈極冰"),
        ("Umbral Hearts", "靈極心"),
        ("Black Mana", "黑魔元"),
        ("White Mana", "白魔元"),
        ("Heat Gauge", "熱度量譜"),
        ("Battery Gauge", "電能量譜"),
        ("Beast Gauge", "獸魂量譜"),
        ("Blood Gauge", "暗血量譜"),
        ("Oath Gauge", "忠義量譜"),
        ("Ninki Gauge", "忍氣量譜"),
        ("Kenki Gauge", "劍氣量譜"),
        ("Chakra Gauge", "鬥氣量譜"),
        ("Faerie Gauge", "異想以太量譜"),
        ("Palette Gauge", "調色盤量譜"),
        ("Soul Gauge", "靈魂量譜"),
        ("Shroud Gauge", "夜遊魂量譜"),
        ("Elemental Gauge", "元素量譜"),
        ("Balance Gauge", "平衡量譜"),
        ("Gauge", "量譜"),
        ("Stacks", "層數"),
        ("Stack", "層數"),
        ("Timer", "計時器"),
        ("Gems", "寶石"),
        ("Gem", "寶石"),
        ("Bar", "量條"),
        ("Counter", "計數器"),
        ("Overlay", "覆蓋層"),
        ("Backplate", "底板"),
        ("Frame", "框架"),
        ("Color", "顏色"),
        ("Tint", "色調"),
        ("Position", "位置"),
        ("Scale", "縮放"),
        ("Hide ", "隱藏"),
        ("Show ", "顯示"),
        ("Move ", "移動"),
        ("Reposition ", "重新定位"),
    ];

    public static string Translate(string text)
    {
        if (string.IsNullOrEmpty(text))
            return text;

        var separator = text.IndexOf("##", StringComparison.Ordinal);
        var visible = separator >= 0 ? text[..separator] : text;
        var id = separator >= 0 ? text[separator..] : string.Empty;

        if (Exact.TryGetValue(visible, out var exact))
            return exact + id;

        var translated = visible;
        foreach (var (english, chinese) in Terms)
            translated = translated.Replace(english, chinese, StringComparison.Ordinal);

        return translated + id;
    }
}
